# Generated by Django 4.2.7 on 2023-12-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Unidades_disponibles',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.BooleanField(default=True),
        ),
    ]
