# Generated by Django 4.2.7 on 2023-12-10 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_producto_unidades_disponibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Unidades_disponibles',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/productos/'),
        ),
    ]
